<?xml version='1.0' encoding='UTF-8'?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://serviciosWeb/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://serviciosWeb/" name="ServicioEnfermedadSW">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://serviciosWeb/" schemaLocation="ServicioEnfermedadSWPort1.xsd"/>
    </xsd:schema>
  </types>
  <message name="agregarEnfermedad">
    <part name="parameters" element="tns:agregarEnfermedad"/>
  </message>
  <message name="agregarEnfermedadResponse">
    <part name="parameters" element="tns:agregarEnfermedadResponse"/>
  </message>
  <message name="listarEnfermedades">
    <part name="parameters" element="tns:listarEnfermedades"/>
  </message>
  <message name="listarEnfermedadesResponse">
    <part name="parameters" element="tns:listarEnfermedadesResponse"/>
  </message>
  <portType name="ServicioEnfermedadSW">
    <operation name="agregarEnfermedad">
      <input wsam:Action="http://serviciosWeb/ServicioEnfermedadSW/agregarEnfermedadRequest" message="tns:agregarEnfermedad"/>
      <output wsam:Action="http://serviciosWeb/ServicioEnfermedadSW/agregarEnfermedadResponse" message="tns:agregarEnfermedadResponse"/>
    </operation>
    <operation name="listarEnfermedades">
      <input wsam:Action="http://serviciosWeb/ServicioEnfermedadSW/listarEnfermedadesRequest" message="tns:listarEnfermedades"/>
      <output wsam:Action="http://serviciosWeb/ServicioEnfermedadSW/listarEnfermedadesResponse" message="tns:listarEnfermedadesResponse"/>
    </operation>
  </portType>
  <binding name="ServicioEnfermedadSWPortBinding" type="tns:ServicioEnfermedadSW">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="agregarEnfermedad">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
    <operation name="listarEnfermedades">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ServicioEnfermedadSW">
    <port name="ServicioEnfermedadSWPort" binding="tns:ServicioEnfermedadSWPortBinding">
      <soap:address location="http://192.168.1.70:7101/AplicacionServidorHospitalSW-ProyectoServidorHospitalSW-context-root/ServicioEnfermedadSWPort"/>
    </port>
  </service>
</definitions>