
package vista;

/**
 *
 * @author crist
 */
public class GUIListarEnfermedades extends javax.swing.JFrame {
    GUIAgregarHistorialClinico padre;
    /** Creates new form GUIListarEnfermedades */
    public GUIListarEnfermedades(GUIAgregarHistorialClinico pPadre) {
        initComponents();
        this.setLocationRelativeTo(null);
       padre = pPadre;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListarEnfermedad = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista De Enfermedades");

        jTableListarEnfermedad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Tipo"
            }
        ));
        jTableListarEnfermedad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListarEnfermedadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListarEnfermedad);
        if (jTableListarEnfermedad.getColumnModel().getColumnCount() > 0) {
            jTableListarEnfermedad.getColumnModel().getColumn(0).setHeaderValue("Codigo");
            jTableListarEnfermedad.getColumnModel().getColumn(1).setHeaderValue("Nombre");
            jTableListarEnfermedad.getColumnModel().getColumn(2).setHeaderValue("Tipo");
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
        );

        pack();
    }//GEN-END:initComponents

    private void jTableListarEnfermedadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListarEnfermedadMouseClicked
        int column = 0;
            
              int row = jTableListarEnfermedad.getSelectedRow();
              String value = jTableListarEnfermedad.getModel().getValueAt(row, column).toString();
              
              padre.txtCodigoEnfermedad.setText(value);
              this.dispose();
    }//GEN-LAST:event_jTableListarEnfermedadMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util
                .logging
                .Logger
                .getLogger(GUIListarEnfermedades.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util
                .logging
                .Logger
                .getLogger(GUIListarEnfermedades.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util
                .logging
                .Logger
                .getLogger(GUIListarEnfermedades.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util
                .logging
                .Logger
                .getLogger(GUIListarEnfermedades.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable() {
                public void run() {
                    //new GUIListarEnfermedades().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableListarEnfermedad;
    // End of variables declaration//GEN-END:variables

}
