
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author crist
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /** Creates new form GUIPrincipal */
    public GUIPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuPaciente = new javax.swing.JMenu();
        jMenuAgregarPaciente = new javax.swing.JMenuItem();
        jMenuListarPaciente = new javax.swing.JMenuItem();
        jMenuListarParametro = new javax.swing.JMenuItem();
        jMenuBuscarPaciente = new javax.swing.JMenuItem();
        jMenuModificarPaciente = new javax.swing.JMenuItem();
        jMenuEliminarPaciente = new javax.swing.JMenuItem();
        jMenuHistorialClinico = new javax.swing.JMenu();
        jMenuAgregarHistorial = new javax.swing.JMenuItem();
        jMenuListarHistorial = new javax.swing.JMenuItem();
        jMenuListarPHistorial = new javax.swing.JMenuItem();
        jMenuBuscarHistorial = new javax.swing.JMenuItem();
        jMenuModificarrHistorial = new javax.swing.JMenuItem();
        jMenuEliminarHistorial = new javax.swing.JMenuItem();
        Ayuda = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Principal");

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenuPaciente.setText("Paciente");

        jMenuAgregarPaciente.setText("Agregar");
        jMenuPaciente.add(jMenuAgregarPaciente);

        jMenuListarPaciente.setText("Listar");
        jMenuPaciente.add(jMenuListarPaciente);

        jMenuListarParametro.setText("Listar Por Parametro");
        jMenuPaciente.add(jMenuListarParametro);

        jMenuBuscarPaciente.setText("Buscar");
        jMenuBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBuscarPacienteActionPerformed(evt);
            }
        });
        jMenuPaciente.add(jMenuBuscarPaciente);

        jMenuModificarPaciente.setText("Modificar");
        jMenuPaciente.add(jMenuModificarPaciente);

        jMenuEliminarPaciente.setText("Eliminar");
        jMenuPaciente.add(jMenuEliminarPaciente);

        jMenuBar1.add(jMenuPaciente);

        jMenuHistorialClinico.setText("Historial Clinico");

        jMenuAgregarHistorial.setText("Agregar");
        jMenuAgregarHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAgregarHistorialActionPerformed(evt);
            }
        });
        jMenuHistorialClinico.add(jMenuAgregarHistorial);

        jMenuListarHistorial.setText("Listar");
        jMenuListarHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListarHistorialActionPerformed(evt);
            }
        });
        jMenuHistorialClinico.add(jMenuListarHistorial);

        jMenuListarPHistorial.setText("Listar Por Parametro");
        jMenuListarPHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListarPHistorialActionPerformed(evt);
            }
        });
        jMenuHistorialClinico.add(jMenuListarPHistorial);

        jMenuBuscarHistorial.setText("Buscar");
        jMenuHistorialClinico.add(jMenuBuscarHistorial);

        jMenuModificarrHistorial.setText("Modificar");
        jMenuModificarrHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuModificarrHistorialActionPerformed(evt);
            }
        });
        jMenuHistorialClinico.add(jMenuModificarrHistorial);

        jMenuEliminarHistorial.setText("Eliminar");
        jMenuEliminarHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEliminarHistorialActionPerformed(evt);
            }
        });
        jMenuHistorialClinico.add(jMenuEliminarHistorial);

        jMenuBar1.add(jMenuHistorialClinico);

        Ayuda.setText("Ayuda");

        jMenuItem2.setText("Acerca de...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Ayuda.add(jMenuItem2);

        jMenuBar1.add(Ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        pack();
    }//GEN-END:initComponents

    private void jMenuBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBuscarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBuscarPacienteActionPerformed

    private void jMenuAgregarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAgregarHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAgregarHistorialActionPerformed

    private void jMenuListarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListarHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuListarHistorialActionPerformed

    private void jMenuModificarrHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuModificarrHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuModificarrHistorialActionPerformed

    private void jMenuEliminarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEliminarHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuEliminarHistorialActionPerformed

    private void jMenuListarPHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListarPHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuListarPHistorialActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Proyecto Realizado por Cristian Silva ( 2220171014) y Steven Rodriguez (2220171024)");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util
                .logging
                .Logger
                .getLogger(GUIPrincipal.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util
                .logging
                .Logger
                .getLogger(GUIPrincipal.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util
                .logging
                .Logger
                .getLogger(GUIPrincipal.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util
                .logging
                .Logger
                .getLogger(GUIPrincipal.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable() {
                public void run() {
                    new GUIPrincipal().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ayuda;
    private javax.swing.JMenu jMenu1;
    public javax.swing.JMenuItem jMenuAgregarHistorial;
    public javax.swing.JMenuItem jMenuAgregarPaciente;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuBuscarHistorial;
    public javax.swing.JMenuItem jMenuBuscarPaciente;
    public javax.swing.JMenuItem jMenuEliminarHistorial;
    public javax.swing.JMenuItem jMenuEliminarPaciente;
    public javax.swing.JMenu jMenuHistorialClinico;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JMenuItem jMenuListarHistorial;
    public javax.swing.JMenuItem jMenuListarPHistorial;
    public javax.swing.JMenuItem jMenuListarPaciente;
    public javax.swing.JMenuItem jMenuListarParametro;
    public javax.swing.JMenuItem jMenuModificarPaciente;
    public javax.swing.JMenuItem jMenuModificarrHistorial;
    public javax.swing.JMenu jMenuPaciente;
    // End of variables declaration//GEN-END:variables

}
