
package serviciosweb;

import java.util.List;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "HistorialClinicoSW", targetNamespace = "http://serviciosWeb/")
@XmlSeeAlso({ ObjectFactory.class })
public interface HistorialClinicoSW {


    /**
     *
     * @param arg0
     * @return
     *     returns serviciosweb.HistorialClinico
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarHistorialSolo", targetNamespace = "http://serviciosWeb/",
                    className = "serviciosweb.BuscarHistorialSolo")
    @ResponseWrapper(localName = "buscarHistorialSoloResponse", targetNamespace = "http://serviciosWeb/",
                     className = "serviciosweb.BuscarHistorialSoloResponse")
    @Action(input = "http://serviciosWeb/HistorialClinicoSW/buscarHistorialSoloRequest",
            output = "http://serviciosWeb/HistorialClinicoSW/buscarHistorialSoloResponse")
    public HistorialClinico buscarHistorialSolo(@WebParam(name = "arg0", targetNamespace = "") int arg0);

    /**
     *
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarHistorial", targetNamespace = "http://serviciosWeb/",
                    className = "serviciosweb.ListarHistorial")
    @ResponseWrapper(localName = "listarHistorialResponse", targetNamespace = "http://serviciosWeb/",
                     className = "serviciosweb.ListarHistorialResponse")
    @Action(input = "http://serviciosWeb/HistorialClinicoSW/listarHistorialRequest",
            output = "http://serviciosWeb/HistorialClinicoSW/listarHistorialResponse")
    public List<HistorialClinico> listarHistorial();

    /**
     *
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "agregarHistorial", targetNamespace = "http://serviciosWeb/",
                    className = "serviciosweb.AgregarHistorial")
    @ResponseWrapper(localName = "agregarHistorialResponse", targetNamespace = "http://serviciosWeb/",
                     className = "serviciosweb.AgregarHistorialResponse")
    @Action(input = "http://serviciosWeb/HistorialClinicoSW/agregarHistorialRequest",
            output = "http://serviciosWeb/HistorialClinicoSW/agregarHistorialResponse")
    public int agregarHistorial(@WebParam(name = "arg0", targetNamespace = "") HistorialClinico arg0);

    /**
     *
     * @param arg1
     * @param arg0
     * @return
     *     returns serviciosweb.HistorialClinico
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarHistorial", targetNamespace = "http://serviciosWeb/",
                    className = "serviciosweb.BuscarHistorial")
    @ResponseWrapper(localName = "buscarHistorialResponse", targetNamespace = "http://serviciosWeb/",
                     className = "serviciosweb.BuscarHistorialResponse")
    @Action(input = "http://serviciosWeb/HistorialClinicoSW/buscarHistorialRequest",
            output = "http://serviciosWeb/HistorialClinicoSW/buscarHistorialResponse")
    public HistorialClinico buscarHistorial(@WebParam(name = "arg0", targetNamespace = "") int arg0,
                                            @WebParam(name = "arg1", targetNamespace = "") String arg1);

    /**
     *
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarHistorialPorParametro", targetNamespace = "http://serviciosWeb/",
                    className = "serviciosweb.ListarHistorialPorParametro")
    @ResponseWrapper(localName = "listarHistorialPorParametroResponse", targetNamespace = "http://serviciosWeb/",
                     className = "serviciosweb.ListarHistorialPorParametroResponse")
    @Action(input = "http://serviciosWeb/HistorialClinicoSW/listarHistorialPorParametroRequest",
            output = "http://serviciosWeb/HistorialClinicoSW/listarHistorialPorParametroResponse")
    public List<HistorialClinico> listarHistorialPorParametro(@WebParam(name = "arg0", targetNamespace = "") String arg0);

    /**
     *
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modificarHistorial", targetNamespace = "http://serviciosWeb/",
                    className = "serviciosweb.ModificarHistorial")
    @ResponseWrapper(localName = "modificarHistorialResponse", targetNamespace = "http://serviciosWeb/",
                     className = "serviciosweb.ModificarHistorialResponse")
    @Action(input = "http://serviciosWeb/HistorialClinicoSW/modificarHistorialRequest",
            output = "http://serviciosWeb/HistorialClinicoSW/modificarHistorialResponse")
    public int modificarHistorial(@WebParam(name = "arg0", targetNamespace = "") HistorialClinico arg0,
                                  @WebParam(name = "arg1", targetNamespace = "") int arg1);

    /**
     *
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "eliminarHistorial", targetNamespace = "http://serviciosWeb/",
                    className = "serviciosweb.EliminarHistorial")
    @Action(input = "http://serviciosWeb/HistorialClinicoSW/eliminarHistorial")
    public void eliminarHistorial(@WebParam(name = "arg0", targetNamespace = "") int arg0);

}
