
package serviciosweb;

import java.util.List;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "PacienteSW", targetNamespace = "http://serviciosWeb/")
@XmlSeeAlso({ ObjectFactory.class })
public interface PacienteSW {


    /**
     *
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "agregarPaciente", targetNamespace = "http://serviciosWeb/",
                    className = "serviciosweb.AgregarPaciente")
    @ResponseWrapper(localName = "agregarPacienteResponse", targetNamespace = "http://serviciosWeb/",
                     className = "serviciosweb.AgregarPacienteResponse")
    @Action(input = "http://serviciosWeb/PacienteSW/agregarPacienteRequest",
            output = "http://serviciosWeb/PacienteSW/agregarPacienteResponse")
    public int agregarPaciente(@WebParam(name = "arg0", targetNamespace = "") Paciente arg0);

    /**
     *
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "eliminarPaciente", targetNamespace = "http://serviciosWeb/",
                    className = "serviciosweb.EliminarPaciente")
    @Action(input = "http://serviciosWeb/PacienteSW/eliminarPaciente")
    public void eliminarPaciente(@WebParam(name = "arg0", targetNamespace = "") String arg0);

    /**
     *
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listar", targetNamespace = "http://serviciosWeb/", className = "serviciosweb.Listar")
    @ResponseWrapper(localName = "listarResponse", targetNamespace = "http://serviciosWeb/",
                     className = "serviciosweb.ListarResponse")
    @Action(input = "http://serviciosWeb/PacienteSW/listarRequest",
            output = "http://serviciosWeb/PacienteSW/listarResponse")
    public List<Paciente> listar();

    /**
     *
     * @param arg0
     * @return
     *     returns serviciosweb.Paciente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarPaciente", targetNamespace = "http://serviciosWeb/",
                    className = "serviciosweb.BuscarPaciente")
    @ResponseWrapper(localName = "buscarPacienteResponse", targetNamespace = "http://serviciosWeb/",
                     className = "serviciosweb.BuscarPacienteResponse")
    @Action(input = "http://serviciosWeb/PacienteSW/buscarPacienteRequest",
            output = "http://serviciosWeb/PacienteSW/buscarPacienteResponse")
    public Paciente buscarPaciente(@WebParam(name = "arg0", targetNamespace = "") String arg0);

    /**
     *
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modificarPaciente", targetNamespace = "http://serviciosWeb/",
                    className = "serviciosweb.ModificarPaciente")
    @ResponseWrapper(localName = "modificarPacienteResponse", targetNamespace = "http://serviciosWeb/",
                     className = "serviciosweb.ModificarPacienteResponse")
    @Action(input = "http://serviciosWeb/PacienteSW/modificarPacienteRequest",
            output = "http://serviciosWeb/PacienteSW/modificarPacienteResponse")
    public int modificarPaciente(@WebParam(name = "arg0", targetNamespace = "") Paciente arg0,
                                 @WebParam(name = "arg1", targetNamespace = "") String arg1);

    /**
     *
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarPorParametro", targetNamespace = "http://serviciosWeb/",
                    className = "serviciosweb.ListarPorParametro")
    @ResponseWrapper(localName = "listarPorParametroResponse", targetNamespace = "http://serviciosWeb/",
                     className = "serviciosweb.ListarPorParametroResponse")
    @Action(input = "http://serviciosWeb/PacienteSW/listarPorParametroRequest",
            output = "http://serviciosWeb/PacienteSW/listarPorParametroResponse")
    public List<Paciente> listarPorParametro(@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
