package serviciosweb;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.4.0.2248
public class PacienteSWPortClient {
    public static void main(String[] args) {
        ServicioPacienteSW servicioPacienteSW = new ServicioPacienteSW();
        PacienteSW pacienteSW = servicioPacienteSW.getPacienteSWPort();
        // Add your code to call the desired methods.


    }
}
