
package serviciosweb;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ServicioEnfermedadSW", targetNamespace = "http://serviciosWeb/",
                  wsdlLocation =
                  "http://192.168.1.70:7101/AplicacionServidorHospitalSW-ProyectoServidorHospitalSW-context-root/ServicioEnfermedadSWPort?WSDL#%7Bhttp%3A%2F%2FserviciosWeb%2F%7DServicioEnfermedadSW")
public class ServicioEnfermedadSW_Service extends Service {

    private final static URL SERVICIOENFERMEDADSW_WSDL_LOCATION;
    private final static WebServiceException SERVICIOENFERMEDADSW_EXCEPTION;
    private final static QName SERVICIOENFERMEDADSW_QNAME = new QName("http://serviciosWeb/", "ServicioEnfermedadSW");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://192.168.1.70:7101/AplicacionServidorHospitalSW-ProyectoServidorHospitalSW-context-root/ServicioEnfermedadSWPort?WSDL#%7Bhttp%3A%2F%2FserviciosWeb%2F%7DServicioEnfermedadSW");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOENFERMEDADSW_WSDL_LOCATION = url;
        SERVICIOENFERMEDADSW_EXCEPTION = e;
    }

    public ServicioEnfermedadSW_Service() {
        super(__getWsdlLocation(), SERVICIOENFERMEDADSW_QNAME);
    }

    public ServicioEnfermedadSW_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOENFERMEDADSW_QNAME, features);
    }

    public ServicioEnfermedadSW_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOENFERMEDADSW_QNAME);
    }

    public ServicioEnfermedadSW_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOENFERMEDADSW_QNAME, features);
    }

    public ServicioEnfermedadSW_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioEnfermedadSW_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ServicioEnfermedadSW
     */
    @WebEndpoint(name = "ServicioEnfermedadSWPort")
    public ServicioEnfermedadSW getServicioEnfermedadSWPort() {
        return super.getPort(new QName("http://serviciosWeb/", "ServicioEnfermedadSWPort"), ServicioEnfermedadSW.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioEnfermedadSW
     */
    @WebEndpoint(name = "ServicioEnfermedadSWPort")
    public ServicioEnfermedadSW getServicioEnfermedadSWPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviciosWeb/", "ServicioEnfermedadSWPort"), ServicioEnfermedadSW.class,
                             features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOENFERMEDADSW_EXCEPTION != null) {
            throw SERVICIOENFERMEDADSW_EXCEPTION;
        }
        return SERVICIOENFERMEDADSW_WSDL_LOCATION;
    }

}
